import streamlit as st
from excuse import generate_excuse
import random
from duck import translate, serious_translate
import time

st.set_page_config(page_title="Simple but Brilliant!", page_icon="👍", layout="wide")

st.title("Simple but Brilliant!")
st.markdown('<p style="text-align: center; color: #aaa; font-size: 16px;">Stupid tools for stupidly brilliant humans.</p>', unsafe_allow_html=True)

loading = ["Hacking the mainframe...", "Consulting the oracle...", "Summoning the AI spirits...", "Hacking NASA for data...", "Asking the AI gods for wisdom..."
        "Running on hamster power...", "Consulting the magic 8-ball...", "Asking the AI for a coffee break...", "Asking a monkey...", "Talking to god himself..."]

container = st.container(border=True)
with container:
    st.header("AI Excuse Generator 🎮")
    problem = st.text_input("Enter a problem:", placeholder="Why didn't you do your homework?")
    if st.button("Generate Excuse"):
        if not problem:
            st.warning("My brain is empty! Please enter a problem to generate an excuse.")
        # Placeholder for AI excuse generation logic
        else:
            with st.spinner(random.choice(loading)):
                excuse = generate_excuse(problem)
            st.write(excuse)

container = st.container(border=True)
with container:
    st.header("What-The-Duck Translator 🦆")
    sentence = st.text_input("Enter a sentence to translate into duck language:", placeholder="Hello, how are you?")
    if st.checkbox("Serious Mode (All quacks, no words)"):
        if st.button("Translate in Serious Mode 🦆"):
            with st.spinner(random.choice(loading)):
                time.sleep(0.9)
            with st.spinner("Talking to ducks..."):
                time.sleep(0.9)
            sentence = serious_translate(sentence)
            st.write(sentence)
    if st.button("Translate 🦆"):
        with st.spinner(random.choice(loading)):
            time.sleep(0.9)
        with st.spinner("Talking to ducks..."):
            time.sleep(0.9)
        sentence = translate(sentence)
        st.write(sentence)


        
container = st.container(border=True)
with container:
    st.header("Useless Robot Simulator 🤖")
    with open ("robot.txt", "r") as f:
        notes = f.read()
        # each line 
        notes = notes.split("\n")
    
    prompt = st.text_input("Ask AI a question:", placeholder="What is the meaning of life?")
    if st.button("Read Note"):
        if not prompt:
            st.warning("Please ask a question for me to answer as you don't know everything!")
        with st.spinner(random.choice(loading)):
            time.sleep(0.9)
        st.write(random.choice(notes))

container = st.container(border=True)
with container:
    st.header("Random Decision Generator 🎲")
    decision = st.text_input("Enter a decision to make:", placeholder="Should I go outside or stay inside?")
    if st.button("Make a Decision"):
        if not decision:
            st.warning("Please enter a decision to make!")
        with st.spinner(random.choice(loading)):
            time.sleep(0.9)
        with open ("desicion.txt", "r") as f:
            decisions = f.read()
            decisions = decisions.split("\n")
        st.write(random.choice(decisions))

container = st.container(border=True)
with container:
    st.header("NOTHING AI Detector 🚫")

    sentence = st.text_input("Enter a sentence to check if it's generated by NOTHING AI:", placeholder="This is a test sentence.")
    if st.button("Check for NOTHING AI"):
        if not sentence:
            st.warning("Please enter something to check.")
            with st.spinner(random.choice(loading)):
                time.sleep(0.9)
        with st.spinner("Analyzing the sentence..."):
            time.sleep(0.9)
         
        if len(sentence) % 2 == 0:
            st.warning("This text is generated by AI. Run for your life!")
        elif sentence == "7":
            st.success("This text is 0% AI generated. You are safe!")
        else:
            st.error("This text is 200% AI generated. You are doomed!")

